server:
  port: 8080
spring:
  datasource:
    seven_quizzes:
      jdbcUrl: jdbc:postgresql://localhost:5432/lpr
      username: lpr_admin
      password: lpr_pass
      driver-class-name: org.postgresql.Driver