
services:
  db:
    image: postgres:16-alpine
    container_name: lpr_postgres
    env_file:
      - ".env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - hardboard-data:/var/lib/postgresql/data
    networks:
      - app-network
  app:
    image: 'docker-spring-boot-postgres:latest'
    container_name: lpr_spring
    build:
      context: .
    env_file:
      - ".env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  hardboard-data:

networks:
  app-network:
