services:
  postgresql:
    container_name: "lpr_postgresql"
    image: postgres:16-alpine
    env_file:
      "./postgres.env"
    ports:
      - '5432:5432'
    volumes:
      - hardboard-data:/var/lib/postgresql/data

volumes:
  hardboard-data: